added confirmation to validate whether firebase credentials file is created

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -45,9 +45,6 @@ jobs:
           restore-keys: |
             build-${{ runner.os }}-
 
-      - name: Download dependencies
-        run: ./gradlew build --build-cache --no-daemon
-
       - name: Build APK
         run: ./gradlew assembleRelease --build-cache --no-daemon
 
@@ -55,6 +52,14 @@ jobs:
         run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase-service-account.json
         # This step retrieves the Firebase service account credentials from the GitHub secret
         # and saves it to a file that will be used in the upload step.
+      - name: Check File Creation
+        run: |
+          if [ -f $HOME/firebase-service-account.json ]; then
+            echo "File firebase-service-account.json created successfully."
+          else
+            echo "Error: File firebase-service-account.json not created."
+            exit 1
+          fi
 
       - name: Upload APK to Firebase App Distribution
         run: ./gradlew appDistributionUploadRelease --build-cache --no-daemon
